# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a4j_tdRK_llmqF6KUcIXK-TwMMPq-rrj
"""

#HackBio Task1 REKHA BOHRA


print("My name is Rekha Bohra")
print("My email address is 19rekhabohra@gmail.com")
print ("The language I use is Python")
print ("My Biostack is Genomics and Drug designing")
print ("My slack user name is @rekbohr")